/**
 * beta2-copy.mjs — the board's own voice.
 *
 * The production content modules are written for the live site and are shared
 * with beta1, so they cannot be re-voiced without changing pages that are
 * already out there. This module is beta2's own layer: it overrides the copy
 * the reader actually reads first — the hero, every chapter head, the three
 * disciplines, the four stages, the three guarantees and every call to action.
 * Anything not overridden here still comes from the production modules, so the
 * eight routines, the integration groups and the team keep one source of truth.
 *
 * Voice, per the brand manual's tone of voice (section 9): friendly,
 * encouraging, human, optimistic — "Mluvíme lidsky. Dodáváme výsledky."
 * In practice, on an enterprise board, that means:
 *
 *   - say the thing the reader is actually worried about, in their words
 *   - one idea per sentence, and the sentence ends when the idea does
 *   - name what we do, not what we "enable" or "leverage"
 *   - confidence comes from specifics — a number, a system, a named person —
 *     never from adjectives about ourselves
 *   - it is fine to be warm; it is not fine to be vague
 */

export const voice = {
  cs: {
    hero: {
      eyebrow: "Podnikové AI · software · automatizace",
      h1: "Stavíme podnikové AI a software, které obstojí v provozu.",
      ctaPrimary: "Probrat projekt",
      ctaSecondary: "Hledám dodací tým",
      lead: "75 specialistů na vývoj, AI, data, integrace a cloud. Navrhujeme, stavíme a dlouhodobě provozujeme komplexní systémy pro velké firmy a technologické partnery po celém světě.",
      note: "120+ dokončených projektů · 60+ integrovaných systémů · 75 specialistů",
    },
    chapters: [
      {
        kicker: "Co stavíme",
        title: "Postavíme to. A pak to s vámi provozujeme.",
        ask: "Máte proces, který stojí víc, než by měl. Zvládneme ho celý — od návrhu přes kód až po pondělní ráno v provozu. Tři odbornosti, jeden dodací tým, jedna odpovědnost za výsledek.",
      },
      {
        kicker: "Ověřené scénáře",
        title: "Začněte tím, co vás štve nejvíc.",
        ask: "Tyhle procesy jsme řešili opakovaně. Známe jejich typické vstupy, výjimky i integrační nároky, takže rychleji ověříme proveditelnost, dopad a rozsah řešení.",
      },
      {
        kicker: "Výsledky",
        title: "Systémy, které už prokazatelně fungují v provozu.",
        ask: "Každé řešení níže běží v reálném prostředí. Uvádíme konkrétní rozsah, použité systémy a změřený dopad — ne výkon na demu.",
      },
      {
        kicker: "Jak pracujeme",
        title: "Nejdřív důkaz. Velké peníze až potom.",
        ask: "První dvě fáze jsou otázka týdnů. Pilot je čtyři týdny až několik měsíců podle toho, kolik systémů a výjimek ten proces doopravdy má — a radši to řekneme dopředu než v půlce. Každá fáze má konec, výstup a rozhodnutí, takže v každé z nich můžete říct dost.",
      },
      {
        kicker: "Integrace",
        title: "Nemusíte měnit nic z toho, co máte.",
        ask: "Váš stack zůstává, jak je. Napojíme se přes API, databázi nebo soubory — a když nic z toho není, tak i přes obrazovku. Zvládli jsme to u víc než 60 systémů, včetně pořádných veteránů.",
      },
      {
        kicker: "Provoz a záruky",
        title: "Po spuštění nezmizíme.",
        ask: "Ještě před zahájením projektu definujeme provozní odpovědnost, reakční doby, vlastnictví kódu a dat i postup předání při ukončení spolupráce.",
      },
      {
        kicker: "Kdo jsme",
        title: "75 specialistů. Jeden tým, jedna odpovědnost.",
        ask: "Není to síť externistů. Jedna firma, jedna smlouva a jmenovité vedení zakázky, které za výsledek odpovídá.",
      },
      {
        kicker: "Váš krok",
        title: "Řekněte nám, co vás brzdí.",
        ask: "Můžete si to napřed spočítat sami, nebo se rovnou zeptat. Půl hodiny stačí na to, abychom vám na rovinu řekli, jestli se do toho vyplatí jít.",
      },
    ],
    disciplines: [
      { title: "Sofistikované automatizace", text: "Rutina, která dnes žere lidem hodiny, běží sama. Výjimky jdou na člověka — a přesně tam, kde je potřeba.",
        list: ["Doklady rovnou do ERP", "CRM a ERP v jednom rytmu", "Schvalování s auditní stopou"] },
      { title: "AI agenti v provozu", text: "Agent dostane cíl, hranice a nástroje a sám volí kroky. Citlivé věci schvaluje člověk a každý zásah je dohledatelný.",
        list: ["Vytěžování dokumentů a e-mailů", "Znalostní agenti, kteří citují zdroj", "Reporting nad ERP běžnou řečí"] },
      { title: "Řešení na míru", text: "Když krabicový software nestačí: vlastní aplikace, integrační a datová vrstva — a provoz, který za to ručí i po spuštění.",
        list: ["Vlastní aplikace a portály", "Integrace i na systémy bez API", "Provoz pod SLA s konkrétním vlastníkem"] },
    ],
    stages: [
      { title: "Najdeme, kde to opravdu drhne", text: "Zmapujeme objem práce, výjimky, data a to, co vás dnešní postup reálně stojí." , time: "1–2 týdny" },
      { title: "Spočítáme, jestli se to vyplatí", text: "Výchozí stav, očekávaná úspora, rizika a jasná podmínka, kdy je pilot úspěšný." , time: "2–3 týdny" },
      { title: "Postavíme pilot na ostrých datech", text: "Napojíme ho na skutečné systémy a přínos změříme na skutečné práci, ne na demu." , time: "4 týdny až několik měsíců" },
      { title: "Převezmeme provoz", text: "Monitoring, bezpečnost, SLA i další rozvoj. Má to konkrétního vlastníka a ten se jmenuje." , time: "průběžně, roky" },
    ],
    ops: [
      { title: "Ručíme za běh", text: "Dostupnost, reakční doby, dohled 24/7, zálohy i aktualizace pod jedním SLA." },
      { title: "Vlastnictví je vyřešené předem", text: "Ve smlouvě je černé na bílém, komu patří kód, data i dokumentace — a dohodne se to dřív, než se začne stavět, ne až na konci. Součástí je i postup předání při ukončení spolupráce." },
      { title: "Bezpečnost řešíme v návrhu", text: "EU cloud nebo on-premise, šifrování, role, oprávnění a auditní stopa, kterou přečte i auditor." },
    ],
    labels: {
      stepLabel: "Fáze",
      proofLabel: "Firma ve třech číslech",
      leadersEyebrow: "Vedení",
      buildGo: "Tři disciplíny, jeden tým →",
      solutionsGo: "Všech osm rutin →",
      processGo: "Čtyři fáze detailně →",
      systemsGo: "Celý přehled systémů →",
      opsGo: "Podmínky a SLA →",
      clientsLabel: "Vybraní klienti",
      partnersLabel: "Partneři",
      facesLabel: "Lidé, kteří to staví",
      flowNodes: [["Doklad", "přijde"], ["Vytěžení", "přečte"], ["Kontrola", "proti ERP"], ["Člověk", "schválí"], ["ERP", "zapsáno"]],
      vizLabel: "Živý tok",
      vizFoot: "dokladů zpracovaných dnes",
      footAsk: "Máte dotaz?",
      footBook: "Rezervovat 30 minut",
      footGroup: "Enter Group",
      standupEyebrow: "Jak se u nás rozhoduje",
      standupTitle: "Tok se kreslí na tabuli dřív, než se píše kód.",
      standupSub: "Požadavek, vývoj, code review, schválení, ERP, deploy. Než se něco postaví, nakreslíme to a projdeme spolu — a v tu chvíli se ukáže, kde chybí rozhodnutí a kdo ho má udělat.",
      standupAlt: "Tři vývojáři u tabule s nakresleným tokem",
      supportEyebrow: "Po spuštění",
      supportTitle: "Někdo to zvedne.",
      supportSub: "Provoz není adresa podpory. Je to konkrétní člověk, který zná váš systém — s definovanou eskalací a zastupitelností.",
      supportAlt: "Člověk z delivery týmu u svého pracovního místa",
      teamGo: "Poznat celý tým →",
      roiGo: "Otevřít kalkulačku →",
      selfGo: "Zjistit svou úroveň →",
      reachGo: "Partnerství pro US →",
      hiringGo: "Volné pozice →",
      agentsGo: "Jak stavíme agenty →",
      selfEyebrow: "Firma 2030 · sebehodnocení",
      selfTitle: "Kde je vaše firma na cestě k agentnímu provozu?",
      selfSub: "Pět úrovní zralosti a jeden praktický krok, který vás posune na další.",
      reachEyebrow: "EU delivery partner",
      reachTitle: "Evropský tým připravený na globální dodávku.",
      reachSub: "Za námi stojí reference evropských enterprise firem i menších a středních podniků. Komunikace a dokumentace v angličtině, smlouvy a fakturace v EUR nebo USD, pravidelné překrytí s americkým pracovním dnem.",
      reachList: ["Tři odbornosti pod jednou dodávkou", "Hosting a datová rezidence podle architektury", "Vzdálená dodávka jako standard, na místě tam, kde to pomůže"],
      hiringPill: "Hledáme lidi",
      hiringTitle: "Stavějte systémy, které opravdu naběhnou.",
      hiringSub: "Dodáte to do provozu a pak to provozujete — a to je ta práce, která za to stojí.",
      bubbleSay: "Řekněte nám proces, který vás brzdí. Řekneme vám na rovinu, jestli se ho vyplatí automatizovat.",
      startPress: "zmáčkni enter",
      artHint: "Sem přijde fotka",
    },
  },

  en: {
    hero: {
      eyebrow: "Enterprise AI · Software Engineering · Automation",
      h1: "Enterprise AI and software engineering, built for production.",
      ctaPrimary: "Discuss a project",
      ctaSecondary: "Extend my delivery team",
      lead: "A 75-person team across software, AI, data, integrations and cloud. We design, build and operate complex systems for enterprises and technology partners worldwide.",
      note: "120+ projects delivered · 60+ systems integrated · 75 specialists",
    },
    chapters: [
      {
        kicker: "What we build",
        title: "We build it. Then we run it with you.",
        ask: "You have a process that costs more than it should. We can take the whole thing — design, code, and Monday morning in production. Three practices, one delivery team, one accountable partner.",
      },
      {
        kicker: "Proven use cases",
        title: "Start with whatever annoys you most.",
        ask: "We have delivered these patterns before. We understand their typical inputs, exceptions and integration requirements, which lets us validate feasibility, value and scope faster.",
      },
      {
        kicker: "Results",
        title: "Systems delivering measurable results in production.",
        ask: "Every solution below runs in a real operating environment. We show the scope, the systems involved and the measured outcome — not benchmark performance from a demo.",
      },
      {
        kicker: "How we work",
        title: "Proof first. Scale the commitment after the evidence.",
        ask: "The first two stages are a matter of weeks. The pilot is four weeks to several months depending on how many systems and exception paths the process really has — and we would rather say that now than halfway through. Every stage has an end, an output and a decision, so at every one of them you can say stop.",
      },
      {
        kicker: "Integrations",
        title: "You do not have to change a thing you already have.",
        ask: "Your stack stays as it is. We connect through the API, the database or the files — and where none of that exists, through the screen. We have done it with more than 60 systems, including legacy systems without a modern API.",
      },
      {
        kicker: "Operations and guarantees",
        title: "We do not disappear at go-live.",
        ask: "Before delivery begins, we agree on operational ownership, response times, code and data rights and the handover process if the engagement ends.",
      },
      {
        kicker: "Who we are",
        title: "75 specialists. One team, one accountable partner.",
        ask: "This is not a network of freelancers. One company, one contract, and named engagement leadership accountable for the outcome.",
      },
      {
        kicker: "Your move",
        title: "Tell us what is slowing you down.",
        ask: "Size it yourself first, or just ask. Half an hour is enough for us to tell you straight whether this is worth doing at all.",
      },
    ],
    disciplines: [
      { title: "Sophisticated automation", text: "The routine that eats your people's hours runs itself. Exceptions go to a person, exactly where a person is needed.",
        list: ["Documents straight into the ERP", "CRM and ERP in step", "Approvals with an audit trail"] },
      { title: "AI agents in production", text: "An agent gets a goal, a boundary and a set of tools, and picks the steps itself. A human approves anything sensitive, and every action stays traceable.",
        list: ["Document and email extraction", "Knowledge agents that cite the source", "Plain-language reporting over the ERP"] },
      { title: "Custom-built solutions", text: "For where off-the-shelf software runs out: your own application, the integration and data layer under it, and operations that answer for it after launch.",
        list: ["Your own applications and portals", "Integration even where there is no API", "Operations under SLA, with a named owner"] },
    ],
    stages: [
      { title: "Find where it actually hurts", text: "We map the volume of work, the exceptions, the data, and what today's way of doing it really costs you." , time: "1–2 weeks" },
      { title: "Work out whether it pays", text: "Baseline, expected saving, risks, and a clear condition for calling the pilot a success." , time: "2–3 weeks" },
      { title: "Build the pilot on real data", text: "We connect it to the real systems and measure the benefit on real work, not on a demo." , time: "4 weeks to several months" },
      { title: "Take over operations", text: "Monitoring, security, SLA and further development. It has a specific owner, and that owner has a name." , time: "ongoing, for years" },
    ],
    ops: [
      { title: "We answer for uptime", text: "Availability, response times, 24/7 monitoring, backups and updates, all under one SLA." },
      { title: "Ownership is settled before we build", text: "The contract says in plain words who owns the code, the data and the documentation — agreed before the work starts rather than at the end. The handover procedure is part of it." },
      { title: "Security is part of the design", text: "EU cloud or on-premise, encryption, roles, permissions, and an audit trail your auditor can actually read." },
    ],
    labels: {
      stepLabel: "Stage",
      proofLabel: "EnterIT in three numbers",
      leadersEyebrow: "Leadership",
      buildGo: "Three disciplines, one team →",
      solutionsGo: "All eight routines →",
      processGo: "The four stages in detail →",
      systemsGo: "The whole catalog →",
      opsGo: "Terms and SLA →",
      clientsLabel: "Selected clients",
      partnersLabel: "Partners",
      facesLabel: "The people who build it",
      flowNodes: [["Document", "arrives"], ["Extraction", "reads it"], ["Check", "against the ERP"], ["A person", "approves"], ["ERP", "written"]],
      vizLabel: "The flow, live",
      vizFoot: "documents processed today",
      footAsk: "Got a question?",
      footBook: "Book 30 minutes",
      footGroup: "Enter Group",
      standupEyebrow: "How a decision gets made here",
      standupTitle: "The flow goes on the whiteboard before it goes into code.",
      standupSub: "Request, development, code review, approval, ERP, deploy. Before anything is built we draw it and walk it together — and that is the moment the missing decision shows up, along with who has to make it.",
      standupAlt: "Three engineers at a whiteboard with the flow drawn out",
      supportEyebrow: "After go-live",
      supportTitle: "Someone picks up.",
      supportSub: "Operations is not a support address. It is a specific person who knows your system — with a defined escalation path and cover.",
      supportAlt: "Someone from the delivery team at their desk",
      teamGo: "Meet the whole team →",
      roiGo: "Open the calculator →",
      selfGo: "Find your level →",
      reachGo: "US partnership →",
      hiringGo: "Open roles →",
      agentsGo: "How we build agents →",
      selfEyebrow: "Firma 2030 · self-check",
      selfTitle: "Where is your company on the agentic road?",
      selfSub: "Five maturity levels, and the one practical step that moves you to the next.",
      reachEyebrow: "EU delivery partner",
      reachTitle: "A European team built for global delivery.",
      reachSub: "Behind us are European enterprise references and small and mid-sized ones too. English-first communication and documentation, contracts and invoicing in EUR or USD, regular overlap with the US working day.",
      reachList: ["Three practices under one delivery model", "Hosting and data residency defined by the architecture", "Remote delivery by default, on-site where it adds value"],
      hiringPill: "We are hiring",
      hiringTitle: "Build systems that actually go live.",
      hiringSub: "You ship it to production and then you run it — which is the job worth having.",
      bubbleSay: "Tell us the process that is slowing your team down. We will tell you straight whether it is worth automating.",
      startPress: "press enter",
      artHint: "Photo goes here",
    },
  },

  de: {
    hero: {
      eyebrow: "Enterprise-KI · Software-Engineering · Automatisierung",
      h1: "Enterprise-KI und Software, gebaut für den Produktivbetrieb.",
      ctaPrimary: "Projekt besprechen",
      ctaSecondary: "Delivery-Team erweitern",
      lead: "Ein Team von 75 Spezialistinnen und Spezialisten für Software, KI, Daten, Integrationen und Cloud. Wir konzipieren, bauen und betreiben komplexe Systeme für Unternehmen und Technologiepartner weltweit.",
      note: "120+ umgesetzte Projekte · 60+ integrierte Systeme · 75 Spezialisten",
    },
    chapters: [
      {
        kicker: "Was wir bauen",
        title: "Wir bauen es. Und betreiben es dann mit Ihnen.",
        ask: "Sie haben einen Prozess, der mehr kostet als nötig. Wir übernehmen ihn ganz — Entwurf, Code und der Montagmorgen im Betrieb. Drei Disziplinen, ein Delivery-Team, eine Verantwortung für das Ergebnis.",
      },
      {
        kicker: "Bewährte Szenarien",
        title: "Fangen Sie mit dem an, was Sie am meisten stört.",
        ask: "Nichts davon ist Raketenwissenschaft, und das meiste haben wir schon gebaut. Finden Sie Ihre Routine, und Sie sehen sofort, was hineingeht und was herauskommt.",
      },
      {
        kicker: "Ergebnisse",
        title: "Systeme mit messbaren Ergebnissen im Produktivbetrieb.",
        ask: "Jede Lösung unten läuft in einer realen Betriebsumgebung. Wir zeigen Umfang, beteiligte Systeme und das gemessene Ergebnis — keine Demo-Werte.",
      },
      {
        kicker: "So arbeiten wir",
        title: "Erst der Beweis. Das große Geld danach.",
        ask: "Die ersten beiden Phasen sind eine Frage von Wochen. Der Pilot dauert vier Wochen bis mehrere Monate, je nachdem wie viele Systeme und Ausnahmen der Prozess wirklich hat — und das sagen wir lieber jetzt als auf halbem Weg. Jede Phase hat ein Ende, ein Ergebnis und eine Entscheidung, in jeder können Sie Schluss sagen.",
      },
      {
        kicker: "Integrationen",
        title: "Sie müssen nichts ändern, was Sie schon haben.",
        ask: "Ihr Stack bleibt, wie er ist. Wir binden über API, Datenbank oder Dateien an — und wo es nichts davon gibt, über die Oberfläche. Bei über 60 Systemen hat das geklappt, darunter echte Veteranen.",
      },
      {
        kicker: "Betrieb und Garantien",
        title: "Nach dem Go-live verschwinden wir nicht.",
        ask: "Bevor die Umsetzung beginnt, legen wir Betriebsverantwortung, Reaktionszeiten, Code- und Datenrechte sowie den Übergabeprozess bei Vertragsende fest.",
      },
      {
        kicker: "Wer wir sind",
        title: "75 Spezialisten. Ein Team, eine Verantwortung.",
        ask: "Kein Netzwerk von Freelancern. Ein Unternehmen, ein Vertrag und eine benannte Projektleitung, die für das Ergebnis einsteht.",
      },
      {
        kicker: "Ihr Zug",
        title: "Sagen Sie uns, was Sie ausbremst.",
        ask: "Rechnen Sie es zuerst selbst durch oder fragen Sie einfach. Eine halbe Stunde reicht, damit wir Ihnen offen sagen, ob sich das überhaupt lohnt.",
      },
    ],
    disciplines: [
      { title: "Anspruchsvolle Automatisierung", text: "Die Routine, die Ihren Leuten heute Stunden frisst, läuft von selbst. Ausnahmen gehen an einen Menschen — genau dort, wo einer gebraucht wird.",
        list: ["Belege direkt ins ERP", "CRM und ERP im Gleichtakt", "Freigaben mit Audit-Trail"] },
      { title: "KI-Agenten im Echtbetrieb", text: "Ein Agent bekommt ein Ziel, eine Grenze und Werkzeuge und wählt die Schritte selbst. Sensibles genehmigt ein Mensch, jede Aktion bleibt nachvollziehbar.",
        list: ["Dokumenten- und E-Mail-Extraktion", "Wissensagenten, die die Quelle nennen", "Reporting über das ERP in normaler Sprache"] },
      { title: "Maßgeschneiderte Lösungen", text: "Für den Punkt, an dem Standardsoftware endet: eigene Anwendung, die Integrations- und Datenschicht darunter, und ein Betrieb, der auch danach dafür haftet.",
        list: ["Eigene Anwendungen und Portale", "Integration auch ohne API", "Betrieb unter SLA, mit benannter Verantwortlichkeit"] },
    ],
    stages: [
      { title: "Finden, wo es wirklich weh tut", text: "Wir erfassen Arbeitsvolumen, Ausnahmen, Daten und das, was der heutige Weg Sie tatsächlich kostet." , time: "1–2 Wochen" },
      { title: "Ausrechnen, ob es sich lohnt", text: "Ausgangslage, erwartete Einsparung, Risiken und eine klare Bedingung, wann der Pilot erfolgreich ist." , time: "2–3 Wochen" },
      { title: "Den Piloten auf echten Daten bauen", text: "Wir binden ihn an die echten Systeme an und messen den Nutzen an echter Arbeit, nicht an einer Demo." , time: "4 Wochen bis mehrere Monate" },
      { title: "Den Betrieb übernehmen", text: "Monitoring, Sicherheit, SLA und Weiterentwicklung — mit einer benannten verantwortlichen Person." , time: "laufend, über Jahre" },
    ],
    ops: [
      { title: "Wir haften für den Betrieb", text: "Verfügbarkeit, Reaktionszeiten, Überwachung rund um die Uhr, Backups und Updates unter einem SLA." },
      { title: "Eigentum ist vorab geregelt", text: "Im Vertrag steht im Klartext, wem Code, Daten und Dokumentation gehören — vereinbart, bevor gebaut wird, nicht erst am Ende. Der Übergabeprozess gehört dazu." },
      { title: "Sicherheit gehört in den Entwurf", text: "EU-Cloud oder on-premise, Verschlüsselung, Rollen, Berechtigungen und ein Audit-Trail, den Ihr Prüfer wirklich lesen kann." },
    ],
    labels: {
      stepLabel: "Phase",
      proofLabel: "Das Haus in drei Zahlen",
      leadersEyebrow: "Führung",
      buildGo: "Drei Disziplinen, ein Team →",
      solutionsGo: "Alle acht Routinen →",
      processGo: "Die vier Phasen im Detail →",
      systemsGo: "Der ganze Katalog →",
      opsGo: "Bedingungen und SLA →",
      clientsLabel: "Ausgewählte Kunden",
      partnersLabel: "Partner",
      facesLabel: "Die Menschen dahinter",
      flowNodes: [["Beleg", "kommt an"], ["Extraktion", "liest ihn"], ["Prüfung", "gegen das ERP"], ["Ein Mensch", "genehmigt"], ["ERP", "geschrieben"]],
      vizLabel: "Der Fluss, live",
      vizFoot: "Belege heute verarbeitet",
      footAsk: "Eine Frage?",
      footBook: "30 Minuten buchen",
      footGroup: "Enter Group",
      standupEyebrow: "Wie hier entschieden wird",
      standupTitle: "Der Ablauf steht am Whiteboard, bevor er im Code steht.",
      standupSub: "Anforderung, Entwicklung, Code Review, Freigabe, ERP, Deploy. Bevor etwas gebaut wird, zeichnen wir es und gehen es gemeinsam durch — und genau dann zeigt sich die fehlende Entscheidung und wer sie treffen muss.",
      standupAlt: "Drei Entwickler am Whiteboard mit dem aufgezeichneten Ablauf",
      supportEyebrow: "Nach dem Go-live",
      supportTitle: "Jemand geht ran.",
      supportSub: "Betrieb ist keine Support-Adresse. Es ist eine bestimmte Person, die Ihr System kennt — mit definierter Eskalation und Vertretung.",
      supportAlt: "Jemand aus dem Delivery-Team am Arbeitsplatz",
      teamGo: "Das ganze Team →",
      roiGo: "Rechner öffnen →",
      selfGo: "Stufe ermitteln →",
      reachGo: "US-Partnerschaft →",
      hiringGo: "Offene Stellen →",
      agentsGo: "Wie wir Agenten bauen →",
      selfEyebrow: "Firma 2030 · Selbstcheck",
      selfTitle: "Wo steht Ihr Unternehmen auf dem Weg zum agentischen Betrieb?",
      selfSub: "Fünf Reifegrade und der eine praktische Schritt zur nächsten Stufe.",
      reachEyebrow: "EU Delivery Partner",
      reachTitle: "Ein europäisches Team, gebaut für globale Lieferung.",
      reachSub: "Hinter uns stehen Referenzen europäischer Konzerne ebenso wie mittelständischer Unternehmen. Kommunikation und Dokumentation auf Englisch, Verträge und Rechnungsstellung in EUR oder USD, regelmäßige Überlappung mit dem US-Arbeitstag.",
      reachList: ["Drei Disziplinen unter einem Liefermodell", "Hosting und Datenresidenz nach der Architektur", "Remote als Standard, vor Ort wo es hilft"],
      hiringPill: "Wir stellen ein",
      hiringTitle: "Systeme bauen, die wirklich live gehen.",
      hiringSub: "Sie liefern in den Produktivbetrieb und betreiben es dann — das ist die Aufgabe, die zählt.",
      bubbleSay: "Nennen Sie uns den Prozess, der Ihr Team bremst. Wir sagen Ihnen offen, ob sich Automatisierung lohnt.",
      startPress: "Enter drücken",
      artHint: "Hier kommt ein Foto",
    },
  },

  pl: {
    hero: {
      eyebrow: "AI dla firm · Software engineering · Automatyzacja",
      h1: "Budujemy firmowe AI i oprogramowanie, które sprawdzają się w produkcji.",
      ctaPrimary: "Porozmawiajmy o projekcie",
      ctaSecondary: "Szukam zespołu delivery",
      lead: "75 specjalistów od oprogramowania, AI, danych, integracji i chmury. Projektujemy, budujemy i długoterminowo utrzymujemy złożone systemy dla dużych firm i partnerów technologicznych na całym świecie.",
      note: "120+ zrealizowanych projektów · 60+ zintegrowanych systemów · 75 specjalistów",
    },
    chapters: [
      {
        kicker: "Co budujemy",
        title: "Zbudujemy to. A potem utrzymujemy razem z wami.",
        ask: "Macie proces, który kosztuje więcej, niż powinien. Weźmiemy go w całości — projekt, kod i poniedziałkowy poranek na produkcji. Trzy specjalizacje, jeden zespół dostawczy, jedna odpowiedzialność za wynik.",
      },
      {
        kicker: "Sprawdzone scenariusze",
        title: "Zacznijcie od tego, co najbardziej irytuje.",
        ask: "Nic z tego nie jest fizyką jądrową, a większość już kiedyś zbudowaliśmy. Znajdźcie swoją rutynę, a od razu zobaczycie, co do niej wchodzi i co z niej wychodzi.",
      },
      {
        kicker: "Wyniki",
        title: "Systemy, które dają mierzalne wyniki na produkcji.",
        ask: "Każde rozwiązanie poniżej działa w realnym środowisku operacyjnym. Pokazujemy zakres, zaangażowane systemy i zmierzony wynik — nie wydajność z dema.",
      },
      {
        kicker: "Jak pracujemy",
        title: "Najpierw dowód. Duże pieniądze później.",
        ask: "Pierwsze dwa etapy to kwestia tygodni. Pilot trwa od czterech tygodni do kilku miesięcy, zależnie od tego, ile systemów i wyjątków proces naprawdę ma — i wolimy powiedzieć to teraz niż w połowie. Każdy etap ma koniec, wynik i decyzję, więc na każdym możecie powiedzieć dość.",
      },
      {
        kicker: "Integracje",
        title: "Nie musicie zmieniać niczego, co już macie.",
        ask: "Wasz stack zostaje taki, jaki jest. Podłączymy się przez API, bazę albo pliki — a gdy nie ma nic z tego, przez ekran. Udało się to przy ponad 60 systemach, w tym prawdziwych weteranach.",
      },
      {
        kicker: "Utrzymanie i gwarancje",
        title: "Po wdrożeniu nie znikamy.",
        ask: "Zanim zacznie się realizacja, ustalamy odpowiedzialność operacyjną, czasy reakcji, prawa do kodu i danych oraz procedurę przekazania na koniec współpracy.",
      },
      {
        kicker: "Kim jesteśmy",
        title: "75 specjalistów. Jeden zespół, jedna odpowiedzialność.",
        ask: "To nie sieć freelancerów. Jedna firma, jedna umowa i imiennie wskazane kierownictwo zlecenia, które odpowiada za wynik.",
      },
      {
        kicker: "Wasz ruch",
        title: "Powiedzcie nam, co was spowalnia.",
        ask: "Policzcie to najpierw sami albo po prostu zapytajcie. Pół godziny wystarczy, żebyśmy powiedzieli wprost, czy w ogóle warto.",
      },
    ],
    disciplines: [
      { title: "Zaawansowane automatyzacje", text: "Rutyna, która dziś zjada waszym ludziom godziny, działa sama. Wyjątki idą do człowieka — dokładnie tam, gdzie jest potrzebny.",
        list: ["Dokumenty prosto do ERP", "CRM i ERP w jednym rytmie", "Zatwierdzanie ze ścieżką audytu"] },
      { title: "Agenci AI na produkcji", text: "Agent dostaje cel, granice i narzędzia i sam wybiera kroki. Wrażliwe rzeczy zatwierdza człowiek, a każde działanie zostaje prześledzone.",
        list: ["Ekstrakcja dokumentów i e-maili", "Agenci wiedzy, którzy cytują źródło", "Raportowanie nad ERP zwykłym językiem"] },
      { title: "Rozwiązania szyte na miarę", text: "Tam, gdzie kończy się pudełkowe oprogramowanie: własna aplikacja, warstwa integracji i danych pod nią, i utrzymanie, które odpowiada za to po starcie.",
        list: ["Własne aplikacje i portale", "Integracja nawet bez API", "Utrzymanie w SLA, z imiennym właścicielem"] },
    ],
    stages: [
      { title: "Znajdujemy, gdzie naprawdę boli", text: "Mapujemy wolumen pracy, wyjątki, dane i to, ile dzisiejszy sposób naprawdę was kosztuje." , time: "1–2 tygodnie" },
      { title: "Liczymy, czy się opłaca", text: "Punkt wyjścia, oczekiwana oszczędność, ryzyka i jasny warunek, kiedy pilot jest udany." , time: "2–3 tygodnie" },
      { title: "Budujemy pilota na prawdziwych danych", text: "Podłączamy go do prawdziwych systemów i mierzymy korzyść na prawdziwej pracy, nie na demie." , time: "4 tygodnie do kilku miesięcy" },
      { title: "Przejmujemy utrzymanie", text: "Monitoring, bezpieczeństwo, SLA i dalszy rozwój. Ma to konkretnego właściciela, a ten właściciel ma imię." , time: "na bieżąco, latami" },
    ],
    ops: [
      { title: "Odpowiadamy za działanie", text: "Dostępność, czasy reakcji, nadzór 24/7, kopie zapasowe i aktualizacje w ramach jednego SLA." },
      { title: "Własność jest ustalona z góry", text: "W umowie stoi czarno na białym, do kogo należy kod, dane i dokumentacja — uzgodnione, zanim zaczniemy budować, a nie na końcu. Procedura przekazania jest jej częścią." },
      { title: "Bezpieczeństwo projektujemy od początku", text: "Chmura UE albo on-premise, szyfrowanie, role, uprawnienia i ścieżka audytu, którą audytor naprawdę przeczyta." },
    ],
    labels: {
      stepLabel: "Etap",
      proofLabel: "Firma w trzech liczbach",
      leadersEyebrow: "Kierownictwo",
      buildGo: "Trzy dyscypliny, jeden zespół →",
      solutionsGo: "Wszystkie osiem rutyn →",
      processGo: "Cztery etapy szczegółowo →",
      systemsGo: "Cały katalog →",
      opsGo: "Warunki i SLA →",
      clientsLabel: "Wybrani klienci",
      partnersLabel: "Partnerzy",
      facesLabel: "Ludzie, którzy to budują",
      flowNodes: [["Dokument", "przychodzi"], ["Ekstrakcja", "czyta"], ["Kontrola", "wobec ERP"], ["Człowiek", "zatwierdza"], ["ERP", "zapisane"]],
      vizLabel: "Przepływ na żywo",
      vizFoot: "dokumentów dziś przetworzonych",
      footAsk: "Masz pytanie?",
      footBook: "Zarezerwuj 30 minut",
      footGroup: "Enter Group",
      standupEyebrow: "Jak zapadają tu decyzje",
      standupTitle: "Przepływ trafia na tablicę, zanim trafi do kodu.",
      standupSub: "Zgłoszenie, rozwój, code review, zatwierdzenie, ERP, deploy. Zanim cokolwiek powstanie, rysujemy to i przechodzimy razem — i to jest moment, w którym wychodzi brakująca decyzja i to, kto ma ją podjąć.",
      standupAlt: "Trzech inżynierów przy tablicy z narysowanym przepływem",
      supportEyebrow: "Po wdrożeniu",
      supportTitle: "Ktoś odbiera.",
      supportSub: "Utrzymanie to nie adres wsparcia. To konkretna osoba, która zna wasz system — ze zdefiniowaną eskalacją i zastępowalnością.",
      supportAlt: "Ktoś z zespołu dostawczego przy swoim biurku",
      teamGo: "Poznaj cały zespół →",
      roiGo: "Otwórz kalkulator →",
      selfGo: "Sprawdź swój poziom →",
      reachGo: "Partnerstwo dla USA →",
      hiringGo: "Otwarte role →",
      agentsGo: "Jak budujemy agentów →",
      selfEyebrow: "Firma 2030 · samoocena",
      selfTitle: "Gdzie jest Twoja firma na drodze do operacji agentowych?",
      selfSub: "Pięć poziomów dojrzałości i jeden praktyczny krok na wyższy.",
      reachEyebrow: "EU delivery partner",
      reachTitle: "Europejski zespół gotowy na globalną dostawę.",
      reachSub: "Za nami stoją referencje europejskich firm enterprise oraz mniejszych i średnich przedsiębiorstw. Komunikacja i dokumentacja po angielsku, umowy i fakturowanie w EUR albo USD, regularne pokrycie z amerykańskim dniem pracy.",
      reachList: ["Trzy specjalizacje w jednym modelu dostawy", "Hosting i rezydencja danych zgodnie z architekturą", "Praca zdalna domyślnie, na miejscu tam, gdzie pomaga"],
      hiringPill: "Rekrutujemy",
      hiringTitle: "Buduj systemy, które naprawdę ruszają.",
      hiringSub: "Wdrażasz na produkcję i potem to utrzymujesz — i to jest praca, która ma sens.",
      bubbleSay: "Powiedzcie nam, który proces was spowalnia. Powiemy wprost, czy warto go automatyzować.",
      startPress: "naciśnij enter",
      artHint: "Tu wejdzie zdjęcie",
    },
  },
};
